### ISSUE TITLE
10/18/21 Presentation Review Ticket

### ISSUE THREAD

**Issue by florayuan18** [devamshri/AllHailTheHolyScrumMaster#47]
Total Scores:
Yajat: 9.5/10
Kyle: 9.5/10
Harry: 9.5/10
Flora: 9.5/10
Devam: 9.5/10

Presentation Score: 4.5/5
Comment Highlights:

1. [Password Encryption](https://github.com/devamshri/AllHailTheHolyScrumMaster/issues/47#issuecomment-945939212)
2. [How to Manage Payment](https://github.com/devamshri/AllHailTheHolyScrumMaster/issues/47#issuecomment-945942609)
3. [Make the Website Cleaner](https://github.com/devamshri/AllHailTheHolyScrumMaster/issues/47#issuecomment-945939896)

ASCII Art Lab:

1. Yajat + Kyle: 3/3
2. Harry, Flora, and Devam: 3/3

Unit 8 Work:

1. Yajat + Kyle: 2/2, [Journal](https://docs.google.com/document/d/1Gc-86BvTlot4jyVBa4iQE2sjUcaYF_pDU6r2joCvn34/edit?usp=sharing)
2. Harry, Flora, and Devam: 2/2, [Journal](https://docs.google.com/document/d/1ZbrZE_7m7otx_fzhOEZwBUQe3HiBdArVGhj036xgOZ4/edit?usp=sharing)

Presentation: https://docs.google.com/presentation/d/1p5L6eX6OFXY06N43C2swB2Pe-GBRLPez-AqjbPAJpeE/edit?usp=sharing

Features:
- [x] Menu
- [x] Slideshows
- [x] Universal Buttons
- [x] Gradient Background

Goals:
- [ ] Implement the Login System
- [ ] Cards for the Menu
- [ ] Automatic Slideshow

**Comment by RohanKoshy** [comment]
I like how you plan to do password encryption so there can be privacy of information on your website.

**Comment by rachelklee** [comment]
I think your color changing feature on the first about us page is really cool. Your idea for your project will be useful for many students

**Comment by chenxin-chex** [comment]
The website's idea is very relevant, and I like the different features of the website, ie adding total cost in the menu page
