### ISSUE TITLE
Devam Individual Final Part 1

### ISSUE THREAD

**Issue by kylem314** [devamshri/AllHailTheHolyScrumMaster#49]
[Link to Devam's Video](https://drive.google.com/file/d/1VpJCmJwhuu7XkbaR5RzEEqIw2ivOBNz9/view?usp=sharing)

[Link to Devam's Presentation](https://docs.google.com/presentation/d/1H4Pct10cxxhu_KIVijEe8X6POLobkIrN0CBAE1xf7oQ/edit#slide=id.p)

**Comment by jm1021** [comment]
The focus of this video was a little backwards... I was hoping for key thing you implemented that was related to CB.  This is more CB thing with a little side reference to PBL.  The video does show knowledge of Arrays and 2D Arrays in these examples.  It would be nice to have seen running code wit a demo.   5.25/6

**Comment by jm1021** [comment]
Your justification comments were very good.  However, my idea was that those comments be directed toward student, not toward me.  I am hoping they would lead to follow up conversations and collaboration.   1.75/2
