### ISSUE TITLE
Flora Individual Final Part 1

### ISSUE THREAD

**Issue by kylem314** [devamshri/AllHailTheHolyScrumMaster#51]
Video: [Link](https://drive.google.com/file/d/1IpSaC4hq5yYpPdarc-s1UdeZZdz5cl7j/view?usp=sharing)
Presentation: [Link](https://docs.google.com/presentation/d/1Owqe39zdl7hTKWJke0EBLt9tyRxjpwhQ_2DQnvZJcLA/edit?usp=sharing)

**Comment by jm1021** [comment]
Hurts my head to hear speed up.  Don't consider this professional and I turned it off at 45 seconds.  Too bad as it seems you had some good material 3/6.

**Comment by jm1021** [comment]
Comments look ok, not sure the build collaboration and follow up conversations.  1.75/2
