### ISSUE TITLE
Harry Individual Final Part 1

### ISSUE THREAD

**Issue by kylem314** [devamshri/AllHailTheHolyScrumMaster#52]
video: https://drive.google.com/file/d/1bzXR8J3BbkEwd9cK4SKu-PavU29g0U6t/view?usp=sharing
presentation: https://docs.google.com/presentation/d/1P75z75s5IOiXX3jvdhyDL2vnMM4QKe4f7v274st5Iso/edit#slide=id.p

**Comment by jm1021** [comment]
I refuse to watch video on speed up.  Also, I have asked that video be made available to those with link.  Frustrated 3/6

**Comment by jm1021** [comment]
comments are pretty short, not very constructive.  probably not enough info to build dialog or collaboration follow up 1.5/2
