### ISSUE TITLE
Kyle Individual Final Part 1

### ISSUE THREAD

**Issue by kylem314** [devamshri/AllHailTheHolyScrumMaster#53]
Video: https://drive.google.com/file/d/1LfZxcPo65rhP0wa2GVI_lgy-quNO3B1w/view?usp=sharing

Slides: https://docs.google.com/presentation/d/1eul02yEE_TxqsVqnAqfSzVeNKyLBVTMUeafyRSi4Yas/edit?usp=sharing

**Comment by jm1021** [comment]
Kyle, I refuse to watch 3 minutes of video where I only understand 1 of 4 words.  3/6

**Comment by jm1021** [comment]
comments are good, not to level of you and David collaborating and expressing opinions 1.75/2
